customhost = "focs-website.c1efdodxxtlq.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "ugavemechills"
customdb = "focs-website"
custombucket = "focs-bucket"
customregion = "us-east-1"
